/* helloworld.c generated by valac 0.52.2, the Vala compiler
 * generated from helloworld.vala, do not modify */

/* helloworld.vala*/
/*   My first vala app*/
/**/
/* Compile:*/
/*   $ valac -o helloworld helloworld.vala*/
/**/

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <stdio.h>

#define TYPE_HELLO_VALA (hello_vala_get_type ())
#define HELLO_VALA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_HELLO_VALA, HelloVala))
#define HELLO_VALA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_HELLO_VALA, HelloValaClass))
#define IS_HELLO_VALA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_HELLO_VALA))
#define IS_HELLO_VALA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_HELLO_VALA))
#define HELLO_VALA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_HELLO_VALA, HelloValaClass))

typedef struct _HelloVala HelloVala;
typedef struct _HelloValaClass HelloValaClass;
typedef struct _HelloValaPrivate HelloValaPrivate;
enum  {
	HELLO_VALA_0_PROPERTY,
	HELLO_VALA_NUM_PROPERTIES
};
static GParamSpec* hello_vala_properties[HELLO_VALA_NUM_PROPERTIES];

struct _HelloVala {
	GObject parent_instance;
	HelloValaPrivate * priv;
};

struct _HelloValaClass {
	GObjectClass parent_class;
};

static gpointer hello_vala_parent_class = NULL;

GType hello_vala_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (HelloVala, g_object_unref)
gint hello_vala_main (gchar** args,
                      gint args_length1);
HelloVala* hello_vala_new (void);
HelloVala* hello_vala_construct (GType object_type);
static GType hello_vala_get_type_once (void);

gint
hello_vala_main (gchar** args,
                 gint args_length1)
{
	FILE* _tmp0_;
	gint result = 0;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Hello world!\n");
	result = 0;
	return result;
}

int
main (int argc,
      char ** argv)
{
	return hello_vala_main (argv, argc);
}

HelloVala*
hello_vala_construct (GType object_type)
{
	HelloVala * self = NULL;
	self = (HelloVala*) g_object_new (object_type, NULL);
	return self;
}

HelloVala*
hello_vala_new (void)
{
	return hello_vala_construct (TYPE_HELLO_VALA);
}

static void
hello_vala_class_init (HelloValaClass * klass,
                       gpointer klass_data)
{
	hello_vala_parent_class = g_type_class_peek_parent (klass);
}

static void
hello_vala_instance_init (HelloVala * self,
                          gpointer klass)
{
}

static GType
hello_vala_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (HelloValaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) hello_vala_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (HelloVala), 0, (GInstanceInitFunc) hello_vala_instance_init, NULL };
	GType hello_vala_type_id;
	hello_vala_type_id = g_type_register_static (G_TYPE_OBJECT, "HelloVala", &g_define_type_info, 0);
	return hello_vala_type_id;
}

GType
hello_vala_get_type (void)
{
	static volatile gsize hello_vala_type_id__volatile = 0;
	if (g_once_init_enter (&hello_vala_type_id__volatile)) {
		GType hello_vala_type_id;
		hello_vala_type_id = hello_vala_get_type_once ();
		g_once_init_leave (&hello_vala_type_id__volatile, hello_vala_type_id);
	}
	return hello_vala_type_id__volatile;
}

